<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "scbase"
 *
 * Auto generated by Extension Builder 2014-11-03
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Swisscom base',
	'description' => 'Main files for a website setup',
	'category' => 'templates',
	'author' => 'Huf Daniel, Renggli Jonas, Helfer Dominique',
	'author_email' => 'daniel.huf@swisscom.com, Jonas.Renggli@swisscom.com, Dominique.Helfer@swisscom.com',
	'author_company' => 'Swisscom',
	'state' => 'alpha',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '0.0.1',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
			'extbase' => '6.2',
			'fluid' => '6.2',
			'scheduler' => '6.2',
			'recycler' => '6.2',
			'linkvalidator' => '6.2',
			'realurl' => '1.12.8',
			'caretaker_instance' => '0.5.0'
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);

?>